-- DamageLifeUpdateCache.lua
-- Generated by the optional DamageLife companion updater.
-- Data only; no executable release content is stored here.
DamageLifeUpdateCache = {
    checkedAt = 0,
    latestVersion = "1.3.4.14",
    latestName = "DamageLife 1.3.4.14",
    releaseURL = "https://github.com/VegasGhoul/DamageLife-WotLK/releases/latest",
    assetURL = "",
    publishedAt = "",
    prerelease = false,
    available = false,
    installedVersion = "1.3.4.14",
    source = "bundled-default"
}
