param(
    [switch]$Watch,
    [int]$IntervalSeconds = 900,
    [string]$AddonRoot = ""
)

$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($AddonRoot)) { $AddonRoot = Split-Path -Parent $PSScriptRoot }

$Repo = 'VegasGhoul/DamageLife-WotLK'
$ApiUrl = "https://api.github.com/repos/$Repo/releases/latest"
$CachePath = Join-Path $AddonRoot 'DamageLifeUpdateCache.lua'
$TocPath = Join-Path $AddonRoot 'DamageLife.toc'

function Get-InstalledVersion {
    if (-not (Test-Path $TocPath)) { return '0.0.0.0' }
    $line = Get-Content -LiteralPath $TocPath | Where-Object { $_ -match '^##\s*Version:\s*(.+)$' } | Select-Object -First 1
    if ($line -and $line -match '^##\s*Version:\s*(.+)$') { return $Matches[1].Trim() }
    return '0.0.0.0'
}

function Get-VersionParts([string]$Version) {
    $numbers = @([regex]::Matches(($Version -replace '^v',''), '\d+') | ForEach-Object { [int]$_.Value })
    while ($numbers.Count -lt 4) { $numbers += 0 }
    return @($numbers[0..3])
}

function Compare-Version([string]$A, [string]$B) {
    $va = Get-VersionParts $A; $vb = Get-VersionParts $B
    for ($i = 0; $i -lt 4; $i++) {
        if ($va[$i] -gt $vb[$i]) { return 1 }
        if ($va[$i] -lt $vb[$i]) { return -1 }
    }
    return 0
}

function Escape-Lua([string]$Text) {
    if ($null -eq $Text) { return '' }
    return $Text.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", '\n')
}

function Write-Cache($Release, [string]$Installed) {
    $latest = [string]$Release.tag_name
    $cmp = Compare-Version $latest $Installed
    $available = if ($cmp -gt 0) { 'true' } else { 'false' }
    $asset = ''
    if ($Release.assets -and $Release.assets.Count -gt 0) {
        $zip = $Release.assets | Where-Object { $_.name -match '\.zip$' } | Select-Object -First 1
        if ($zip) { $asset = [string]$zip.browser_download_url }
    }

    $timestamp = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    $content = @"
-- Generated by DamageLifeUpdater.ps1. DATA ONLY.
DamageLifeUpdateCache = {
    checkedAt = $timestamp,
    latestVersion = "$(Escape-Lua $latest)",
    latestName = "$(Escape-Lua ([string]$Release.name))",
    releaseURL = "$(Escape-Lua ([string]$Release.html_url))",
    assetURL = "$(Escape-Lua $asset)",
    publishedAt = "$(Escape-Lua ([string]$Release.published_at))",
    prerelease = $([string]$Release.prerelease).ToLower(),
    available = $available,
    installedVersion = "$(Escape-Lua $Installed)",
    source = "github-companion"
}
"@
    Set-Content -LiteralPath $CachePath -Value $content -Encoding UTF8
    return @{ Latest = $latest; Available = ($cmp -gt 0); URL = [string]$Release.html_url }
}

function Invoke-Check {
    try {
        $installed = Get-InstalledVersion
        $headers = @{ 'User-Agent' = 'DamageLife-Companion-Updater/1.0'; 'Accept' = 'application/vnd.github+json' }
        $release = Invoke-RestMethod -Uri $ApiUrl -Headers $headers -Method Get -TimeoutSec 15
        $result = Write-Cache $release $installed
        if ($result.Available) {
            Write-Host "[UPDATE AVAILABLE] Installed: $installed | Latest: $($result.Latest)"
            Write-Host "Release: $($result.URL)"
        } else {
            Write-Host "[UP TO DATE] Installed: $installed | Latest: $($result.Latest)"
        }
        return $true
    } catch {
        Write-Warning "DamageLife update check failed: $($_.Exception.Message)"
        return $false
    }
}

if ($Watch) {
    while ($true) {
        Invoke-Check | Out-Null
        Start-Sleep -Seconds ([Math]::Max(60, $IntervalSeconds))
    }
} else {
    Invoke-Check | Out-Null
}
